### ISSUE TITLE
Enable contributing page 

### ISSUE THREAD

**Issue by jamesanderson9182** [Playology/fire-testing#9]
## Definition
As a Owner
I need to display contributing information
So that I can more easily get contributors to the project 

## Acceptance Criteria
+ Must display page at https://ngxtend.github.com/fire-testing/contributing 
+ Must include all information necessary in order for a completely new contributor to contribute 

## Extra Information
This will require updating the code in the /docs folder

**Comment by mike-hanson** [comment]
This is already done and a link to it included in the README for the repo.

**Comment by jamesanderson9182** [comment]
@testpossessed that link on the read me doesn’t work yet. I assume there’s something you need to enable.

**Comment by mike-hanson** [comment]
It is working for me although not completely correctly, in terms of it doesn't load the default route correctly and the url is showing an extra level of fire-testing.  But when clicking on the menu items it is showing the correct components.

**Comment by mike-hanson** [comment]
Fixed it, working properly now.
